// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaEstoque.Worker.Database.Context;

#nullable disable

namespace SistemaEstoque.Worker.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20260131140748_DefinidaChavePrimariaDePedidoProcessado")]
    partial class DefinidaChavePrimariaDePedidoProcessado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaEstoque.Worker.Entities.PedidoProcessado", b =>
                {
                    b.Property<Guid>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataProcessamento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PedidoId");

                    b.ToTable("PedidosProcessados");
                });

            modelBuilder.Entity("SistemaEstoque.Worker.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            Nome = "Teclado Mecânico RGB",
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Nome = "Mouse Gamer 12000 DPI",
                            QuantidadeEstoque = 100
                        },
                        new
                        {
                            Id = new Guid("f1234567-89ab-4cde-0123-456789abcdef"),
                            Nome = "Monitor 144Hz",
                            QuantidadeEstoque = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
